name: configcat_client
description: >-
  Dart (Flutter) SDK for ConfigCat. ConfigCat is a hosted feature flag service that lets you manage feature toggles across frontend, backend, mobile, desktop apps.
version: 2.5.0
homepage: https://configcat.com/docs/sdk-reference/dart
repository: https://github.com/configcat/dart-sdk
issue_tracker: https://github.com/configcat/dart-sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dio: ^5.1.2
  logger: ^1.3.0
  pub_semver: ^2.1.4
  json_annotation: ^4.8.1

dev_dependencies:
  test: ^1.24.3
  mockito: ^5.4.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  http_mock_adapter: ">=0.3.3 <0.5.0"
  sprintf: ">=6.0.0 <8.0.0"
  lints: ">=1.0.1 <3.0.0"